os: linux
dist: bionic

language: shell

jobs:
    include:
        - env: CONFIG_DEBIAN_ARCH=armhf
        - env: CONFIG_DEBIAN_ARCH=arm64
        - env: CONFIG_DEBIAN_ARCH=i386
        - env: CONFIG_DEBIAN_ARCH=amd64
        - env: CONFIG_DEBIAN_ARCH=mipsel

# TODO: look into debian bug #952655 and figure out why the newer
#   debian-ports-archive-keyring still doesnt fix the expired key
#   error while multistrap is validating the unstableports repo
#        - env: CONFIG_DEBIAN_ARCH=riscv64 CONFIG_DISTRO=unstableports

branches:
    except:
    - prerelease

install:
    - sudo apt-get update
    - make build-depends
    - sudo update-binfmts --disable
    - dpkg -l binfmt-support
    - dpkg -L binfmt-support
    - sudo rm /var/lib/binfmts/qemu-*
    - sudo sed -i 's/bionic/eoan/g' /etc/apt/sources.list
    - sudo apt-get update
    - sudo apt-get install qemu-user-static
    - cat /proc/sys/fs/binfmt_misc/qemu-arm
    - cat /proc/sys/fs/binfmt_misc/qemu-riscv64

script:
    - make cpio
    - make test CONFIG_DISABLE_KVM=yes

before_deploy:
    - ./scripts/travis_before_deploy || export TRAVIS_TAG=prerelease

deploy:
    provider: releases
    token: "$GITHUB_TOKEN"
    skip_cleanup: true
    release_notes: "Automatic release created by travis-ci integration"
    prerelease: true
    overwrite: true
    file_glob: true
    file:
        - build/debian.*.cpio
    on:
        all_branches: true
        condition: $TRAVIS_BRANCH != prerelease
